var movies = [
	'Alien',
	'Avengers: Endgame',
	'Pulp Fiction',
	'Die Hard',
	'Twilight',
	'Shawshank Redemption',
	'Harold and Kumar Go to White Castle',
	'Bill and Ted\'s Excellent Advenutre',
	'Liar Liar',
	'The Truman Show',
	'The Godfather',
	'Predator',
	'The Excorcist',
	'Full Metal Jacket',
	'The Pianist',
	'Titanic',
	'A Beautiful Mind',
	'A Quiet Place',
	'Air Force One',
	'Airplane!',
	'Amelie',
	'American Beauty',
	'Ant-Man and Wasp',
	'Apocalypto',
	'Bad Boys',
	'Blade',
	'Blues Brothers',
	'Caddyshack',
	'Call Me By Your Name',
	'Captain Phillips',
	'Casino',
	'Casino Royale',
	'Creed',
	'Crocodile Dundee',
	'Crouching Tiger, Hidden Dragon',
	'Dallas Buyers Club',
	'Dances With Wolves',
	'Devil\'s Advocate',
	'Die Hard 3',
	'Dirty Dancing',
	'Do the Right Thing',
	'Dr. Strangelove',
	'Dunkirk',
	'Eighth Grade',
	'Encino Man',
	'Evil Dead',
	'Face/Off',
	'Fargo',
	'Fast and the Furious: Tokyo Drift',
	'Platoon',
	'Point Break',
	'Purple Rain',
	'Raging Bull',
	'Rain Man',
	'Ralph Breaks the Internet',
	'Rambo: First Blood Part II',
	'Rocky', 
	'Saturday Night Fever',
	'Shaft',
	'Solo: A Star Wars Story',
	'Space Jam',
	'Speed',
	'Stand By Me',
	'The Magnificent Seven',
	'The Transporter',
	'Wall Street',
	'Wedding Crashers',
	'White Men Can\'t Jump',
]

function newMovie(){
	var randomNumber = Math.floor(Math.random() * (movies.length));
	document.getElementById('movieDisplay').innerHTML = movies[randomNumber];
}
